# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: f18b90608af4d0c2b603d66963ec2386a3f8af95681dd405ce00bca5f9127710ee591d3dd8db7a9ef134ea0d8dce1792bdefb3e4295995a1e1c67ec3e106e335
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 241977a24a85523a95a46bc9c4abd6561ad83e5f296504188ef9b9185d1be8c3ae079f34ea21f81db24328d5cfae682c09194bd0cbe3d58f26d91779929f0674

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
